### ISSUE TITLE
Is it normal that it only merges the video but not the audio?

### ISSUE THREAD

**Issue by moeC137** [woodruffw/snippets#6]
Not sure if thats normal or an error on my side.

**Comment by woodruffw** [comment]
If you're talking about `ffmpeg-mosaic`, yes:

https://github.com/woodruffw/snippets/blob/0b68529921d476e1b57d36cfdf6c7939b87835a5/ffmpeg-mosaic/ffmpeg-mosaic#L74-L75

You can remove that `-an` member to re-enable audio. You may have to tweak it a bit, since I'm not sure whether ffmpeg will use only the first input's main audio track or whether it'll try to mux them all together.

**Comment by moeC137** [comment]
ok, thx for the info ill try it
edit:
it works only for the first channel

**Comment by woodruffw** [comment]
Cool. Feel free to open a PR that adds any functionality you need, gated off with CLI flags.
